### ISSUE TITLE
updating the logos

### ISSUE THREAD

**Issue by 20ankur07** [arghadipmanna101/Flipkart_Clone#165] opened 2024-05-11 06:23 UTC
Hey @arghadipmanna101 the logo used for twitter is outdated , I think I can update it with new X logo and add instagram social as well if you want . So please assign it to me.

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/125962231/7b7fa4d4-44ef-45b9-b08e-9278284f7f27)

**Comment by drashtiv03** [comment] 2024-05-11 06:29
Please assign this task to me under the label GSSoC'24.

**Comment by ananyabansal16** [comment] 2024-05-11 06:56
Hey, I can update the logos, kindly assign me this issue under the label GSSoC'24.

**Comment by arghadipmanna101** [comment] 2024-05-11 07:08
The issue is solved.

**Closed by arghadipmanna101** 2024-05-11 07:08 UTC
