### ISSUE TITLE
Search bar is not looking good

### ISSUE THREAD

**Issue by Sathya-reddy1658** [arghadipmanna101/Flipkart_Clone#44] opened 2024-05-09 17:10 UTC
when search bar is clicked it's showing some random  distorted border inside the search bar , i can adjust and in addition i can add hover effect and neat shadow effect to make it look appealing

**Comment by arghadipmanna101** [comment] 2024-05-09 17:16
Give me a pic of issues. @Sathya-reddy1658

**Comment by Sathya-reddy1658** [comment] 2024-05-09 17:41
> Give me a pic of issues. @Sathya-reddy1658

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/154568696/ba64d5c5-bae6-4c1a-980d-02fbf9bc1147)
the border has to applied to the outer box , this looks very odd

**Comment by Gokilp** [comment] 2024-05-09 17:45
please assign to me

**Comment by arghadipmanna101** [comment] 2024-05-09 17:48
> > Give me a pic of issues. @Sathya-reddy1658
> 
> ![image](https://private-user-images.githubusercontent.com/154568696/329336719-ba64d5c5-bae6-4c1a-980d-02fbf9bc1147.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNzcxMjgsIm5iZiI6MTcxNTI3NjgyOCwicGF0aCI6Ii8xNTQ1Njg2OTYvMzI5MzM2NzE5LWJhNjRkNWM1LWJhZTYtNGMxYS05ODBkLTAyZmJmOWJjMTE0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxNzQ3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2FhYmViNGI2ZDkyOWZhMzgwNTBkMWZmYzRlMjE5ZDcxOGM2ODI5Yzg5YjM2MzI1ODNhZjA0M2ZkNTU3M2QxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nshwm343Vka5AZ7r-na0GP62XljmH57e1y_UoEomSFg) the border has to applied to the outer box , this looks very odd and also search icon is out of this and looks weird

the issue is already solved.

**Comment by GarimaSingh0109** [comment] 2024-05-10 02:07
PLEASE ASIGN ME THE TASK

**Comment by PoojaGadagi08** [comment] 2024-05-10 03:33
Hello @arghadipmanna101 sir
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.

**Comment by arghadipmanna101** [comment] 2024-05-10 05:46
The search bar is working properly.

**Closed by arghadipmanna101** 2024-05-10 05:46 UTC
