### ISSUE TITLE
Hover effect on buttons on the website.

### ISSUE THREAD

**Issue by alok1304** [arghadipmanna101/Flipkart_Clone#13] opened 2024-05-09 09:51 UTC
There is no hover effect on the website. It seems like our website is not responsive. we can modify this website in much good conditions.

I also attached the screenshot of the website..

![Screenshot 2024-05-09 151522](https://github.com/arghadipmanna101/Flipkart_Clone/assets/143247433/399df32f-e15b-4730-b06e-f7632d47ea70)

**Comment by alok1304** [comment] 2024-05-09 09:53
can you assign this to me , I want to do some work on this project.

**Comment by PadmaSri08** [comment] 2024-05-09 10:27
I want to work on this issue. Please assign it to me so I can use my skills to solve this.

**Comment by arghadipmanna101** [comment] 2024-05-09 11:41
Go ahead guys

**Comment by anushkapal28** [comment] 2024-05-09 12:30
I would like to work on this issue. Can you please assign this to me.

**Comment by kamalesh-og** [comment] 2024-05-09 13:27
Thank You @arghadipmanna101

**Comment by ivarcodes** [comment] 2024-05-09 13:50
Hi  sir i would love to contribute on this issue #13

**Comment by arghadipmanna101** [comment] 2024-05-09 13:51
> Hi sir i would love to contribute on this issue #13

do your best. go ahead @ivarcodes

**Comment by bk408** [comment] 2024-05-09 16:18
Hello  @arghadipmanna101
I want to work on this issue, please assign me

**Closed** 2024-05-09 16:37 UTC
Labels: enhancement, Midium

**Comment by arghadipmanna101** [comment] 2024-05-10 15:24
> i have a doubt since the issue is closed... we shouldn't contribute to it any further? or i can contribute after 7pm anyways?

If the problem close, it means the problem is solved. If you want to work on this problem, you can create a new issue and then explain the problem. ok @kamalesh-og
